apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Values.api.deployment}}"
spec:
  replicas: {{ default 1 .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: "{{.Values.api.name}}"
        version: "{{.Values.api.versionLabel}}"
    spec:
      containers:
      - name: "{{.Values.api.name}}"
        image: "{{.Values.api.image}}:{{.Values.api.imageTag}}"
      imagePullSecrets:
      - name: squillace-acr-auth
        env:
        - name: MONGODB_URI
          value: mongodb://rating-db.default.svc.cluster.local:27017/webratings
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.api.name}}"
  labels:
    app: "{{.Values.api.name}}"
spec:
  type: "{{.Values.api.serviceType}}"
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: "{{.Values.api.name}}"